In [12]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

x_data=[[73.,80.,75.],[93.,88.,93.],
       [89.,91.,90],[96.,98.,100.],[73.,66.,70]]
y_data=[[152.],[185.],[180.],[196.],[142.]]

#placeholders for a tensor that will be always fed.

X=tf.placeholder(tf.float32,shape=[None,3])
Y=tf.placeholder(tf.float32,shape=[None,1])

W=tf.Variable(tf.random_normal([3,1]),name='weight')
b=tf.Variable(tf.random_normal([1]),name='bias')

hypothesis=tf.matmul(X,W)+b



In [13]:
cost=tf.reduce_mean(tf.square(hypothesis-Y))

optimizer=tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

In [15]:
sess=tf.Session()

sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val,_=sess.run([cost,hypothesis,train],
                              feed_dict={X:x_data,Y:y_data})
    if step %10==0:
        print(step,"Cost: ",cost_val,"\nPrediction:\n",hy_val)

0 Cost:  128131.1 
Prediction:
 [[-158.98756]
 [-201.71346]
 [-193.01575]
 [-213.94539]
 [-153.29478]]
10 Cost:  20.156958 
Prediction:
 [[157.62436]
 [178.86168]
 [181.95514]
 [194.3909 ]
 [136.99394]]
20 Cost:  18.888721 
Prediction:
 [[158.56583]
 [180.02438]
 [183.08453]
 [195.62323]
 [137.88655]]
30 Cost:  18.793707 
Prediction:
 [[158.55223]
 [180.03912]
 [183.08287]
 [195.62381]
 [137.90355]]
40 Cost:  18.699274 
Prediction:
 [[158.5358 ]
 [180.05035]
 [183.07776]
 [195.62064]
 [137.91782]]
50 Cost:  18.605356 
Prediction:
 [[158.5194 ]
 [180.06154]
 [183.07266]
 [195.61751]
 [137.93204]]
60 Cost:  18.511879 
Prediction:
 [[158.50302]
 [180.0727 ]
 [183.06757]
 [195.61435]
 [137.94623]]
70 Cost:  18.418955 
Prediction:
 [[158.48672]
 [180.08383]
 [183.06252]
 [195.61125]
 [137.9604 ]]
80 Cost:  18.326563 
Prediction:
 [[158.47046]
 [180.09492]
 [183.05745]
 [195.60811]
 [137.9745 ]]
90 Cost:  18.234615 
Prediction:
 [[158.45424]
 [180.106  ]
 [183.05243]
 [195.605  ]
 [137.9886 

1110 Cost:  11.037636 
Prediction:
 [[157.0073 ]
 [181.09245]
 [182.60208]
 [195.33325]
 [139.2376 ]]
1120 Cost:  10.984801 
Prediction:
 [[156.995  ]
 [181.10088]
 [182.59825]
 [195.33101]
 [139.2482 ]]
1130 Cost:  10.932223 
Prediction:
 [[156.98268]
 [181.10925]
 [182.5944 ]
 [195.32875]
 [139.25873]]
1140 Cost:  10.879942 
Prediction:
 [[156.97043]
 [181.11761]
 [182.59058]
 [195.3265 ]
 [139.26926]]
1150 Cost:  10.827923 
Prediction:
 [[156.95818]
 [181.12593]
 [182.58675]
 [195.32426]
 [139.27974]]
1160 Cost:  10.776205 
Prediction:
 [[156.94598]
 [181.13425]
 [182.58296]
 [195.32204]
 [139.29022]]
1170 Cost:  10.7247715 
Prediction:
 [[156.93384]
 [181.14255]
 [182.57916]
 [195.31982]
 [139.30066]]
1180 Cost:  10.673609 
Prediction:
 [[156.92169]
 [181.1508 ]
 [182.5754 ]
 [195.31761]
 [139.31107]]
1190 Cost:  10.62273 
Prediction:
 [[156.90959]
 [181.15904]
 [182.57161]
 [195.3154 ]
 [139.32143]]
1200 Cost:  10.572088 
Prediction:
 [[156.89752]
 [181.16727]
 [182.56784]
 [195.3