In [4]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
tf.set_random_seed(777) # for reproductivity

xy=np.loadtxt('data-01-test-score.csv',delimiter=',',
              dtype=np.float32)
x_data=xy[:,0:-1]
y_data=xy[:,[-1]]

print(x_data.shape,x_data,len(x_data))
print(y_data.shape,y_data)

X=tf.placeholder(tf.float32,shape=[None,3])
Y=tf.placeholder(tf.float32,shape=[None,1])

W=tf.Variable(tf.random_normal([3,1]),name='weight')
b=tf.Variable(tf.random_normal([1]),name='bias')

hypothesis=tf.matmul(X,W)+b

cost=tf.reduce_mean(tf.square(hypothesis-Y))

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [5]:
optimizer=tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train=optimizer.minimize(cost)

In [6]:
sess=tf.Session()

sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val,_=sess.run([cost,hypothesis,train],
                              feed_dict={X:x_data,Y:y_data})
    if step %10==0:
        print(step,"Cost: ",cost_val,"\nPrediction:\n",hy_val)

0 Cost:  2718.816 
Prediction:
 [[105.63413 ]
 [126.47547 ]
 [125.023895]
 [135.61624 ]
 [ 96.54288 ]
 [ 69.79834 ]
 [100.468285]
 [ 73.146675]
 [117.17079 ]
 [106.953476]
 [ 97.20397 ]
 [ 95.26545 ]
 [129.85419 ]
 [108.63137 ]
 [100.75681 ]
 [127.81018 ]
 [103.965   ]
 [120.55726 ]
 [123.95743 ]
 [110.752945]
 [118.138245]
 [117.99579 ]
 [112.82747 ]
 [108.02509 ]
 [131.53586 ]]
10 Cost:  18.7481 
Prediction:
 [[154.14401 ]
 [184.79321 ]
 [182.47781 ]
 [198.19565 ]
 [141.01659 ]
 [102.600494]
 [147.31891 ]
 [107.88934 ]
 [171.68542 ]
 [157.46558 ]
 [142.33817 ]
 [139.77757 ]
 [189.20432 ]
 [157.95853 ]
 [147.82564 ]
 [186.9951  ]
 [150.9374  ]
 [176.7844  ]
 [180.53601 ]
 [161.37724 ]
 [173.07721 ]
 [172.71234 ]
 [165.2041  ]
 [156.9167  ]
 [191.9697  ]]
20 Cost:  18.519215 
Prediction:
 [[154.46925]
 [185.19733]
 [182.86856]
 [198.62894]
 [141.32167]
 [102.83892]
 [147.6511 ]
 [108.14616]
 [172.07562]
 [157.84532]
 [142.65417]
 [140.09796]
 [189.60028]
 [158.2775 ]
 [148.16217]
 [187

290 Cost:  16.109062 
Prediction:
 [[154.22098 ]
 [185.22781 ]
 [182.71288 ]
 [198.65717 ]
 [141.26349 ]
 [103.13964 ]
 [147.8741  ]
 [108.583984]
 [172.42209 ]
 [158.63283 ]
 [142.76393 ]
 [140.42715 ]
 [189.24252 ]
 [157.7191  ]
 [148.45723 ]
 [187.60051 ]
 [150.56584 ]
 [177.50127 ]
 [180.48705 ]
 [161.33376 ]
 [173.70421 ]
 [173.2989  ]
 [165.71428 ]
 [156.51727 ]
 [192.26945 ]]
300 Cost:  16.029686 
Prediction:
 [[154.21236]
 [185.22867]
 [182.70737]
 [198.6581 ]
 [141.26122]
 [103.14995]
 [147.88191]
 [108.59941]
 [172.43393]
 [158.6601 ]
 [142.7677 ]
 [140.43848]
 [189.22993]
 [157.69951]
 [148.46753]
 [187.6069 ]
 [150.54227]
 [177.51242]
 [180.47223]
 [161.32053]
 [173.71252]
 [173.30574]
 [165.71928]
 [156.49252]
 [192.2653 ]]
310 Cost:  15.950929 
Prediction:
 [[154.20378]
 [185.22952]
 [182.70187]
 [198.659  ]
 [141.25896]
 [103.1602 ]
 [147.88971]
 [108.6148 ]
 [172.44572]
 [158.68723]
 [142.77147]
 [140.44977]
 [189.2174 ]
 [157.68   ]
 [148.47778]
 [187.61331]
 [150.5187

570 Cost:  14.114871 
Prediction:
 [[153.99567]
 [185.24762]
 [182.5676 ]
 [198.68213]
 [141.19965]
 [103.40921]
 [148.08372]
 [108.99771]
 [172.73183]
 [159.3507 ]
 [142.86435]
 [140.72466]
 [188.90974]
 [157.19975]
 [148.73149]
 [187.76842]
 [149.93887]
 [177.80127]
 [180.0959 ]
 [160.98558]
 [173.92654]
 [173.4778 ]
 [165.84938]
 [155.8644 ]
 [192.15791]]
580 Cost:  14.051748 
Prediction:
 [[153.98822]
 [185.24818]
 [182.56276]
 [198.68301]
 [141.19734]
 [103.41814]
 [148.09087]
 [109.01181]
 [172.74211]
 [159.37468]
 [142.86774]
 [140.73457]
 [188.89857]
 [157.1823 ]
 [148.74077]
 [187.77397]
 [149.91771]
 [177.81154]
 [180.08281]
 [160.97397]
 [173.9341 ]
 [173.48373]
 [165.85402]
 [155.84254]
 [192.1541 ]]
590 Cost:  13.989136 
Prediction:
 [[153.9808  ]
 [185.24872 ]
 [182.5579  ]
 [198.68387 ]
 [141.19505 ]
 [103.427025]
 [148.09798 ]
 [109.02587 ]
 [172.7523  ]
 [159.39853 ]
 [142.87111 ]
 [140.74443 ]
 [188.88745 ]
 [157.1649  ]
 [148.75002 ]
 [187.7795  ]
 [149.89662 ]
 [177

 [[153.80118 ]
 [185.25977 ]
 [182.43945 ]
 [198.70592 ]
 [141.13522 ]
 [103.64251 ]
 [148.27545 ]
 [109.375786]
 [172.99983 ]
 [159.98201 ]
 [142.9546  ]
 [140.9848  ]
 [188.61421 ]
 [156.73676 ]
 [148.97894 ]
 [187.91377 ]
 [149.3758  ]
 [178.07765 ]
 [179.75029 ]
 [160.67938 ]
 [174.12859 ]
 [173.633   ]
 [165.97456 ]
 [155.28824 ]
 [192.05484 ]]
860 Cost:  12.477569 
Prediction:
 [[153.79474]
 [185.26007]
 [182.43517]
 [198.70673]
 [141.13293]
 [103.65022]
 [148.282  ]
 [109.38867]
 [173.0087 ]
 [160.00308]
 [142.95766]
 [140.99347]
 [188.60428]
 [156.72118]
 [148.98732]
 [187.91858]
 [149.35677]
 [178.08711]
 [179.73871]
 [160.66917]
 [174.13545]
 [173.63814]
 [165.97885]
 [155.26895]
 [192.0513 ]]
870 Cost:  12.427674 
Prediction:
 [[153.78835]
 [185.26038]
 [182.4309 ]
 [198.70755]
 [141.13063]
 [103.6579 ]
 [148.28851]
 [109.40151]
 [173.01753]
 [160.02406]
 [142.9607 ]
 [141.00209]
 [188.59439]
 [156.70566]
 [148.99567]
 [187.92337]
 [149.33783]
 [178.09653]
 [179.72719]
 [160

1160 Cost:  11.1430235 
Prediction:
 [[153.61707 ]
 [185.26581 ]
 [182.3151  ]
 [198.73087 ]
 [141.06396 ]
 [103.863976]
 [148.46889 ]
 [109.75676 ]
 [173.25415 ]
 [160.5924  ]
 [143.04398 ]
 [141.23474 ]
 [188.32532 ]
 [156.28226 ]
 [149.22495 ]
 [188.05182 ]
 [148.81863 ]
 [178.35847 ]
 [179.41435 ]
 [160.38333 ]
 [174.33096 ]
 [173.78075 ]
 [166.10251 ]
 [154.72897 ]
 [191.94974 ]]
1170 Cost:  11.103838 
Prediction:
 [[153.61162]
 [185.26587]
 [182.31137]
 [198.73163]
 [141.06168]
 [103.87053]
 [148.47482]
 [109.76843]
 [173.26169]
 [160.61069]
 [143.04669]
 [141.24219]
 [188.3166 ]
 [156.26854]
 [149.23244]
 [188.05591]
 [148.80173]
 [178.36713]
 [179.40427]
 [160.37448]
 [174.33714]
 [173.78513]
 [166.10646]
 [154.71219]
 [191.94649]]
1180 Cost:  11.064978 
Prediction:
 [[153.6062 ]
 [185.26593]
 [182.30765]
 [198.73242]
 [141.05939]
 [103.87705]
 [148.48073]
 [109.78007]
 [173.26917]
 [160.62888]
 [143.0494 ]
 [141.2496 ]
 [188.30794]
 [156.25485]
 [149.23988]
 [188.05997]
 [148.

1580 Cost:  9.738936 
Prediction:
 [[153.41212 ]
 [185.26402 ]
 [182.17197 ]
 [198.76245 ]
 [140.96866 ]
 [104.111534]
 [148.70273 ]
 [110.21676 ]
 [173.53827 ]
 [161.29185 ]
 [143.1496  ]
 [141.51866 ]
 [187.9895  ]
 [155.7511  ]
 [149.51715 ]
 [188.20619 ]
 [148.16087 ]
 [178.70096 ]
 [179.02672 ]
 [160.04407 ]
 [174.57358 ]
 [173.94653 ]
 [166.25961 ]
 [154.0848  ]
 [191.82104 ]]
1590 Cost:  9.710857 
Prediction:
 [[153.40779]
 [185.26385]
 [182.16887]
 [198.76315]
 [140.96642]
 [104.11677]
 [148.70793]
 [110.227  ]
 [173.5443 ]
 [161.30692]
 [143.15192]
 [141.52475]
 [187.98221]
 [155.73952]
 [149.52357]
 [188.20944]
 [148.14645]
 [178.70862]
 [179.01834]
 [160.03677]
 [174.57896]
 [173.95006]
 [166.26315]
 [154.07088]
 [191.81815]]
1600 Cost:  9.683029 
Prediction:
 [[153.40347]
 [185.2637 ]
 [182.1658 ]
 [198.76389]
 [140.96417]
 [104.12198]
 [148.71312]
 [110.23718]
 [173.55028]
 [161.3219 ]
 [143.15424]
 [141.53079]
 [187.97495]
 [155.728  ]
 [149.52998]
 [188.2127 ]
 [148.1320

1890 Cost:  8.963886 
Prediction:
 [[153.28854 ]
 [185.25696 ]
 [182.08234 ]
 [198.78418 ]
 [140.8999  ]
 [104.261505]
 [148.8568  ]
 [110.51947 ]
 [173.71033 ]
 [161.72769 ]
 [143.2176  ]
 [141.69391 ]
 [187.777   ]
 [155.41302 ]
 [149.70627 ]
 [188.29977 ]
 [147.73778 ]
 [178.92856 ]
 [178.78336 ]
 [159.83267 ]
 [174.73212 ]
 [174.04744 ]
 [166.36473 ]
 [153.68114 ]
 [191.73518 ]]
1900 Cost:  8.941885 
Prediction:
 [[153.2849  ]
 [185.25665 ]
 [182.07962 ]
 [198.78485 ]
 [140.89772 ]
 [104.26593 ]
 [148.86154 ]
 [110.528755]
 [173.7154  ]
 [161.74072 ]
 [143.21968 ]
 [141.69913 ]
 [187.77058 ]
 [155.4028  ]
 [149.71202 ]
 [188.30252 ]
 [147.72493 ]
 [178.93558 ]
 [178.77603 ]
 [159.82634 ]
 [174.73697 ]
 [174.05042 ]
 [166.36797 ]
 [153.66902 ]
 [191.73251 ]]
1910 Cost:  8.920036 
Prediction:
 [[153.28128 ]
 [185.25636 ]
 [182.07695 ]
 [198.78552 ]
 [140.89554 ]
 [104.270325]
 [148.86624 ]
 [110.538   ]
 [173.72044 ]
 [161.75371 ]
 [143.22173 ]
 [141.70432 ]
 [187.7642  ]
 [155.39261

In [ ]:
#predict score
print("Score will be ",sess.run(hypothesis,
                               feed_dict={X;[[100,80,9]]}))